
import {
  LayoutDashboard,
  Receipt,
  PiggyBank,
  Target,
  Settings,
  BarChart3,
  Landmark,
  Coffee,
  Bus,
  Home,
  Tv,
  Gamepad2,
  GraduationCap,
  ShoppingBag,
  MoreHorizontal,
  DollarSign,
  Wallet,
  Zap,
  Gift,
  Award,
  Apple,
  Car,
  Sparkles,
  Plane,
  Laptop,
  Guitar,
  Shirt,
  Smartphone,
  Camera,
  Bike,
  Pizza,
  Palmtree,
  Trophy,
  Watch,
  Gem,
  Dog,
  Palette,
  Tent,
  Briefcase
} from 'lucide-react';
import React from 'react';
import { Category } from './types';

export const CATEGORY_ICONS: Record<Category, React.ReactNode> = {
  [Category.FOOD]: <Coffee className="w-5 h-5" />,
  [Category.TRAVEL]: <Bus className="w-5 h-5" />,
  [Category.RENT]: <Home className="w-5 h-5" />,
  [Category.UTILITIES]: <Zap className="w-5 h-5" />,
  [Category.SUBSCRIPTIONS]: <Tv className="w-5 h-5" />,
  [Category.ENTERTAINMENT]: <Gamepad2 className="w-5 h-5" />,
  [Category.ACADEMICS]: <GraduationCap className="w-5 h-5" />,
  [Category.SHOPPING]: <ShoppingBag className="w-5 h-5" />,
  [Category.GROCERIES]: <Apple className="w-5 h-5" />,
  [Category.TRANSPORTATION]: <Car className="w-5 h-5" />,
  [Category.PERSONAL_CARE]: <Sparkles className="w-5 h-5" />,
  [Category.OTHER]: <MoreHorizontal className="w-5 h-5" />,
  [Category.INCOME]: <DollarSign className="w-5 h-5" />,
  [Category.INCOME_SOURCE]: <Wallet className="w-5 h-5" />,
  [Category.SCHOLARSHIP]: <Award className="w-5 h-5" />,
  [Category.GIFT]: <Gift className="w-5 h-5" />,
};

export const CATEGORY_COLORS: Record<Category, string> = {
  [Category.FOOD]: 'bg-orange-100 text-orange-600',
  [Category.TRAVEL]: 'bg-blue-100 text-blue-600',
  [Category.RENT]: 'bg-red-100 text-red-600',
  [Category.UTILITIES]: 'bg-yellow-100 text-yellow-600',
  [Category.SUBSCRIPTIONS]: 'bg-purple-100 text-purple-600',
  [Category.ENTERTAINMENT]: 'bg-pink-100 text-pink-600',
  [Category.ACADEMICS]: 'bg-emerald-100 text-emerald-600',
  [Category.SHOPPING]: 'bg-indigo-100 text-indigo-600',
  [Category.GROCERIES]: 'bg-lime-100 text-lime-600',
  [Category.TRANSPORTATION]: 'bg-sky-100 text-sky-600',
  [Category.PERSONAL_CARE]: 'bg-rose-100 text-rose-600',
  [Category.OTHER]: 'bg-slate-100 text-slate-600',
  [Category.INCOME]: 'bg-green-100 text-green-600',
  [Category.INCOME_SOURCE]: 'bg-teal-100 text-teal-600',
  [Category.SCHOLARSHIP]: 'bg-cyan-100 text-cyan-600',
  [Category.GIFT]: 'bg-rose-100 text-rose-600',
};

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { id: 'transactions', label: 'Transactions', icon: Receipt },
  { id: 'budgets', label: 'Budgets', icon: PiggyBank },
  { id: 'goals', label: 'Goals', icon: Target },
  { id: 'investments', label: 'Investments', icon: Landmark },
  { id: 'analytics', label: 'Analytics', icon: BarChart3 },
  { id: 'settings', label: 'Settings', icon: Settings },
];

// Mapping of Goal Icon Keys to Lucide Components
export const GOAL_ICON_COMPONENTS: Record<string, React.ElementType> = {
  'target': Target,
  'travel': Plane,
  'tech': Laptop,
  'car': Car,
  'home': Home,
  'education': GraduationCap,
  'music': Guitar,
  'fashion': Shirt,
  'phone': Smartphone,
  'camera': Camera,
  'bike': Bike,
  'food': Pizza,
  'gift': Gift,
  'savings': PiggyBank,
  'vacation': Palmtree,
  'sport': Trophy,
  'watch': Watch,
  'game': Gamepad2,
  'jewelry': Gem,
  'pet': Dog,
  'art': Palette,
  'camping': Tent,
  'work': Briefcase
};
